\documentclass[12pt]{article}

\usepackage{amsmath}
%\usepackage[authoryear,round]{natbib}
\usepackage{hyperref}

\textwidth=6.2in
\textheight=8.5in
%\parskip=.3cm
\oddsidemargin=.1in
\evensidemargin=.1in
\headheight=-.3in

\newcommand{\scscst}{\scriptscriptstyle}
\newcommand{\scst}{\scriptstyle}
\newcommand{\Rfunction}[1]{{\texttt{#1}}}
\newcommand{\Robject}[1]{{\texttt{#1}}}
\newcommand{\Rpackage}[1]{{\textit{#1}}}

\author{Noemi Andor}
%\VignetteIndexEntry{expands}
\begin{document}
\title{Description of expands}

\maketitle
\tableofcontents
\section{Introduction}
Expanding Ploidy and Allele Frequency on Nested Subpopulations (ExPANdS) characterizes genetically diverse subpopulations in a tumor using copy number and allele frequencies derived from exome- or whole genome sequencing input data \cite{andor}.
Given a set of somatic point mutations,  detected in a tumor sample and the copy number of the mutated loci, ExPANdS identifies the number N of clonal expansions within the tumor, the relative size of the resulting subpopulations in the tumor bulk and the mutations habitant in each subpopulation. Sequencing errors, mapping errors and germline mutations have to be filtered first. The remaining set of somatic mutations can be extended to contain loss of heterozygosity (LOH), that is loci with heterozygous germline polymorphisms where the mutated allele is overrepresented in the cancer cell. For tumor types with a low number of somatic point mutations, this approach can provide a sufficient number of somatic events for the subsequent procedure \cite{andor}. 
The model predicts subpopulations based on two assumptions:
\begin{itemize}
\item Two independent driver-events of the same type will not target the same genomic position in two different cells. Therefore, no more than two distinct cell types exist with respect to a specific locus. 
\item  Multiple passenger mutations accumulate in a cell before a driver mutation causes a clonal expansion. Thus, each clonal expansion is marked by multiple mutations. 
\end{itemize}
These two assumptions are translated into the ExPANdS model in four main steps: cell frequency estimation, clustering, filtering and assignment of mutations to clusters. The following example demonstrates each of these steps separately. All steps are merged in the main function \Rfunction{runExPANdS} provided with the package \Rpackage{expands}.
The robustness of the subpopulation predictions by ExPANdS increases with the number of mutations provided. It is recommended that at least 200 mutations are used as an input to obtain stable results.

\section{Data}
We illustrate the utility of ExPANdS on data derived from exome sequencing of a Glioblastoma tumor (TCGA-06-0152-01) from TCGA. Somatic mutations and LOH have been obtained by applying MuTutect \cite{Cibulskis} on the tumor derived BAM file and the patient-matched normal BAM file. Copy number segments have been obtained by a circular binary segmentation algorithm. We load the data into the workspace and assign each mutation the copy number of the segment in which the mutation is embedded:
<<>>=
library(expands)
##loading mutations
data(snv);
## use only a subset of all mutations (for performance reasons).
set.seed(6); idx=sample(1:nrow(snv), 130, replace=FALSE); snv=snv[idx,];
##loading copy number segments
data(cbs);
##assign copy number to mutations
dm=assignQuantityToMutation(snv,cbs,"CN_Estimate");
@
Note that we limit the number of mutations used to 130 to accelerate the computation. In practice however, the inclusion of all available mutations is recommended, as the robustness and accuracy of the algorithm depends on the completeness of the input.
\section{Parameter Settings}
Next we set the parameters for the subsequent prediction. Type \Rfunction{help(runExPANdS)} for more information on these parameters.
<<>>=
##parameters
max_PM=6; maxScore=2.5; precision=0.018;
plotF=1; 
##the name of the sample
snvF="TCGA-06-0152-01";
@
\section{Predicting coexisting subpopulations with ExPANdS}
Now we are ready to predict the number of clonal expansions in TCGA-06-0152-01, the size of the resulting subpopulations in the tumor bulk and which mutations accumulate in a cell prior to its clonal expansion.
\subsection{Cell frequency estimation}
First we calculates {\it P} - the probability density distribution of cellular frequencies for each single mutation separately. For each cellular frequency {\it f}, the value of {\it P(f)} reflects the probability that the mutation is present in a fraction {\it f} of cells. For more information see \Rfunction{help(cellfrequency\_pdf)}. This step may take several minutes to complete.
<<>>=
##compute the cell frequency probability distribution for each mutation
cfd=computeCellFrequencyDistributions(dm, max_PM, precision)
@
In the subsequent step - \Rfunction{ clusterCellFrequencies} - we will use only those mutations for which the cell frequency estimation was successful:
<<>>=
##cluster mutations with valid distributions
toUseIdx=which(apply(is.finite(cfd$densities),1,all) )
@
In this case the cell-frequency probability distributions could be estimated for all mutations. 
\subsection{Clustering and Filtering}
Next we find overrepresented cell frequencies using a two-step clustering procedure. Based on the assumption that passenger mutations occur within a cell prior to the driver event that initiates the expansion, each clonal expansion should be marked by multiple mutations. 
Thus SNVs and CNVs that took place in a cell prior to a clonal expansion should be present in a similar fraction of cells and leave a similar trace in the subsequent clonal expansion. The aim is to find common peaks in the distribution of $P_l(f)$ for multiple mutated loci {\it l}. In the first step, mutations with similar $P_l(f)$ are grouped together by hierarchical cluster analysis of the probability distributions $P_l(f)$ using the Kullback-Leibler divergence as a distance measure. This step may take several minutes to complete, depending on the number of mutations provided. In the second step, each cluster is extended by members with similar distributions in an interval around the cluster-maxima (core-region). Clusters are pruned based on statistics within and outside the core region \cite{andor}. All these steps are performed within the function \Rfunction{clusterCellFrequencies}:
<<>>=
SPs=clusterCellFrequencies(cfd$densities[toUseIdx,], precision, label=snvF)
@
At this point we already know that five subpopulations have been predicted to coexist in this tumor:
<<>>=
print(SPs)
@
\subsection{Assignment of SNVs to clusters}
Now, all that remains to be done is to assign each mutated locus to one of the predicted subpopulations. A mutated locus {\it l} is assigned to the subpopulation {\it C}, whose size is closest to the maximum likelyhood cellular frequency of {\it l}:
 $C:=argmin_C |argmax_f P_l(f)-f^C|$, where $P_l(f)$ is the probability distribution of cellular frequencies as computed by \Rfunction{cellfrequency\_pdf} and $f^C$ is the size of subpopulation {\it C}. The mutated loci assigned to each subpopulation cluster represent the genetic profile of each predicted subpopulation.
<<>>=
##assign mutations to subpopulations
aM= assignMutations( dm, SPs,cfd$densities)
@
\Robject{aM\$dm} contains the input matrix \Robject{snv} with two additional columns: \Robject{subpopulation} - the size of the subpopulation to which the mutation has been assigned; and \Robject{\%maxP} - confidence of the assignment.

\newpage
\section{Visualization of predicted subpopulations}
Finally we plot the coexistent subpopulations predicted in the previous steps.
\begin{figure}[htbp]
\begin{center}
<<fig=TRUE, width=30, height=16>>=
plotSPs(aM$dm, snvF)
@
\caption{\label{f4.3} 
Coexistent subpopulations determined by ExPANdS in an Glioblastoma genome. Five subpopulations were identified based on the allele-frequency and copy number of 130 mutations detected within the cancer-genome. Subpopulations were present in 96\%, 71\%, 38\%, 28\% and 15\% of the sample (y-axis). For each of the 130 exonic mutations (x-axis) we show: - the subpopulation to which the mutation has been assigned (squares), - the ploidy of the locus in that subpopulation and - the allele frequency of the mutation. Allele frequencies and ploidities are colored based on the chromosome on which the mutation is located (stars - somatic SNVs, triangles - LOH). Subpopulations are colored based on the confidence with which the mutation has been assigned to the subpopulation (black - highest, white - lowest).
}
\end{center}
\end{figure}

\section{Acknowledgements}
Special thanks to Dr. Ruchira S. Datta for her valuable contributions to the structure and presentation of this manuscript.

 \begin{thebibliography}{1}

  \bibitem{andor} Noemi Andor, Julie Harness, Hans Werner Mewes and Claudia Petritsch. {\em ExPANdS: Expanding Ploidy and Allele Frequency on Nested Subpopulations. 
  }  Bioinformatics (2013). In Review.

  \bibitem{Cibulskis}  Cibulskis K, Lawrence MS, Carter SL, Sivachenko A, Jaffe D, Sougnez C, Gabriel S, Meyerson M, Lander ES, Getz G. {\em Sensitive detection of somatic point mutations in impure and heterogeneous cancer samples. 
 } Nat Biotech (2013).

 \end{thebibliography}

\end{document}
